Add cascading delete of inquiries associated with user when user is d…
JohanSaisa/GT pull request #118
Opened 2022-04-06 15:06 UTC by RasmusBroborg

…eleting account. #95.

2022-04-06 15:23 UTC, JohanSaisa requested changes
Review comments per dialogue.

2022-04-06 15:23 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTListingInquiryService.cs
> +			var associatedInquiryIds = await _listingInquiryRepository.GetAll()
Implement try catch

2022-04-06 15:23 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTListingInquiryService.cs
> +				.Where(e => e.ApplicantId == userId)
Implement logger

2022-04-07 06:17 UTC, RasmusBroborg commented on src/GT.Core/Services/Impl/GTListingInquiryService.cs
> +			var associatedInquiryIds = await _listingInquiryRepository.GetAll()
Fixed in commit.

2022-04-07 06:17 UTC, RasmusBroborg commented on src/GT.Core/Services/Impl/GTListingInquiryService.cs
> +				.Where(e => e.ApplicantId == userId)
Fixed in commit.

2022-04-07 08:21 UTC, antoncarlgren approved these changes

2022-04-07 08:59 UTC, JohanSaisa approved these changes
Approve

2022-04-07 09:06 UTC, merged