Split Service interfaces into multiple smaller ones.
JohanSaisa/GT pull request #167
Opened 2022-04-25 11:07 UTC by antoncarlgren

Slight temporary refactoring of CompanyService, as it is the only one with an update method with a return value. Should be re-implemented once services have been refactored as a whole. #165

2022-04-25 11:21 UTC, JohanSaisa reviewed
Please see comments.

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTCompanyService.cs
> +				return await _companyRepository.GetAll().AnyAsync(e => e.Name == name);
Why not just return entity?

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTCompanyService.cs
>  				if (dto.Id != id)
Shouldn't Id check happen before try catch?

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTExperienceLevelService.cs
> +
Write TODO if we should implement interface?

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTExperienceLevelService.cs
> +
Same as above.

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTExperienceLevelService.cs
> +
Same as above.

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTLocationService.cs
TODO if we should implement?

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTLocationService.cs
> +
TODO if we should implement?

2022-04-25 11:21 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/GTLocationService.cs
> +
TODO if we should implement?

2022-04-25 15:33 UTC, RasmusBroborg requested changes
Review build errors before merge with main.

2022-04-26 11:29 UTC, antoncarlgren commented
Closing PR/branch since issue requires more refactoring/work than previously thought, and should arguably be pushed back to a later date.

2022-04-26 11:29 UTC, closed without merging