76 add mail server
JohanSaisa/GT pull request #80
Opened 2022-03-30 14:05 UTC by JohanSaisa

2022-03-30 15:18 UTC, JohanSaisa commented
![](https://github.trello.services/images/mini-trello-icon.png) [US2003: Användare - Inlogg via sociala medier](https://trello.com/c/Ti79gVWs/20-us2003-anv%C3%A4ndare-inlogg-via-sociala-medier)

2022-03-30 17:24 UTC, RasmusBroborg requested changes

2022-03-31 07:25 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/EmailSender.cs
> +		public async Task SendEmailAsync(string email, string subject, string htmlMessage)
Default naming convention from implemented interface IEmailSender - propose we keep this aligned.

2022-03-31 07:27 UTC, JohanSaisa commented on src/GT.Core/Services/Impl/AuthMessageSenderOptions.cs
> +		public string? SendGridKey { get; set; }
Removed in new commit. Residual from when looking to implement Send Grid according to best practice - settled for SMTP as of now.

2022-03-31 08:29 UTC, antoncarlgren approved these changes

2022-03-31 08:32 UTC, RasmusBroborg approved these changes

2022-03-31 08:32 UTC, JohanSaisa commented on src/GT.UI/Program.cs
> +	.AddTransient<IEmailSender, EmailSender>();
Fixed.

2022-03-31 08:33 UTC, merged